package game

var (
	initMoves = []Move{
		{A: State{X: 13, Y: 3}, B: State{X: 12, Y: 4}},
		{A: State{X: 9, Y: 1}, B: State{X: 8, Y: 2}},
		{A: State{X: 1, Y: 8}, B: State{X: 1, Y: 9}},
		{A: State{X: 5, Y: 1}, B: State{X: 4, Y: 2}},
		{A: State{X: 1, Y: 4}, B: State{X: 2, Y: 4}},
		{A: State{X: 9, Y: 1}, B: State{X: 10, Y: 1}},
		{A: State{X: 12, Y: 3}, B: State{X: 12, Y: 4}},
		{A: State{X: 1, Y: 1}, B: State{X: 2, Y: 2}},
		{A: State{X: 2, Y: 2}, B: State{X: 3, Y: 2}},
		{A: State{X: 5, Y: 1}, B: State{X: 6, Y: 1}},
		{A: State{X: 12, Y: 1}, B: State{X: 13, Y: 1}},
		{A: State{X: 7, Y: 1}, B: State{X: 8, Y: 2}},
		{A: State{X: 9, Y: 2}, B: State{X: 10, Y: 2}},
		{A: State{X: 2, Y: 1}, B: State{X: 2, Y: 2}},
		{A: State{X: 13, Y: 8}, B: State{X: 13, Y: 9}},
		{A: State{X: 5, Y: 2}, B: State{X: 6, Y: 2}},
		{A: State{X: 2, Y: 2}, B: State{X: 1, Y: 3}},
		{A: State{X: 12, Y: 7}, B: State{X: 13, Y: 8}},
		{A: State{X: 12, Y: 7}, B: State{X: 13, Y: 7}},
		{A: State{X: 12, Y: 9}, B: State{X: 13, Y: 9}},
		{A: State{X: 11, Y: 1}, B: State{X: 12, Y: 2}},
		{A: State{X: 8, Y: 2}, B: State{X: 9, Y: 2}},
		{A: State{X: 12, Y: 2}, B: State{X: 12, Y: 3}},
		{A: State{X: 13, Y: 3}, B: State{X: 13, Y: 4}},
		{A: State{X: 3, Y: 1}, B: State{X: 3, Y: 2}},
		{A: State{X: 4, Y: 2}, B: State{X: 5, Y: 2}},
		{A: State{X: 1, Y: 3}, B: State{X: 2, Y: 3}},
		{A: State{X: 12, Y: 4}, B: State{X: 12, Y: 5}},
		{A: State{X: 7, Y: 2}, B: State{X: 8, Y: 2}},
		{A: State{X: 6, Y: 1}, B: State{X: 7, Y: 2}},
		{A: State{X: 4, Y: 1}, B: State{X: 3, Y: 2}},
		{A: State{X: 1, Y: 7}, B: State{X: 2, Y: 7}},
		{A: State{X: 1, Y: 8}, B: State{X: 2, Y: 9}},
		{A: State{X: 2, Y: 4}, B: State{X: 1, Y: 5}},
		{A: State{X: 12, Y: 1}, B: State{X: 12, Y: 2}},
		{A: State{X: 12, Y: 8}, B: State{X: 13, Y: 8}},
		{A: State{X: 11, Y: 2}, B: State{X: 12, Y: 2}},
		{A: State{X: 8, Y: 1}, B: State{X: 9, Y: 1}},
		{A: State{X: 10, Y: 1}, B: State{X: 11, Y: 2}},
		{A: State{X: 2, Y: 2}, B: State{X: 2, Y: 3}},
		{A: State{X: 8, Y: 1}, B: State{X: 7, Y: 2}},
		{A: State{X: 1, Y: 5}, B: State{X: 1, Y: 6}},
		{A: State{X: 4, Y: 1}, B: State{X: 5, Y: 1}},
		{A: State{X: 12, Y: 2}, B: State{X: 13, Y: 3}},
		{A: State{X: 1, Y: 2}, B: State{X: 1, Y: 3}},
		{A: State{X: 2, Y: 7}, B: State{X: 1, Y: 8}},
		{A: State{X: 13, Y: 6}, B: State{X: 13, Y: 7}},
		{A: State{X: 3, Y: 1}, B: State{X: 4, Y: 2}},
		{A: State{X: 1, Y: 6}, B: State{X: 1, Y: 7}},
		{A: State{X: 1, Y: 9}, B: State{X: 2, Y: 9}},
		{A: State{X: 7, Y: 1}, B: State{X: 6, Y: 2}},
		{A: State{X: 13, Y: 4}, B: State{X: 12, Y: 5}},
		{A: State{X: 13, Y: 1}, B: State{X: 13, Y: 2}},
		{A: State{X: 12, Y: 4}, B: State{X: 13, Y: 4}},
		{A: State{X: 1, Y: 4}, B: State{X: 2, Y: 5}},
		{A: State{X: 1, Y: 1}, B: State{X: 2, Y: 1}},
		{A: State{X: 13, Y: 7}, B: State{X: 13, Y: 8}},
		{A: State{X: 8, Y: 1}, B: State{X: 8, Y: 2}},
		{A: State{X: 7, Y: 1}, B: State{X: 8, Y: 1}},
		{A: State{X: 4, Y: 1}, B: State{X: 4, Y: 2}},
		{A: State{X: 1, Y: 2}, B: State{X: 2, Y: 2}},
		{A: State{X: 2, Y: 8}, B: State{X: 2, Y: 9}},
		{A: State{X: 1, Y: 5}, B: State{X: 2, Y: 5}},
		{A: State{X: 3, Y: 2}, B: State{X: 4, Y: 2}},
		{A: State{X: 2, Y: 4}, B: State{X: 2, Y: 5}},
		{A: State{X: 11, Y: 1}, B: State{X: 12, Y: 1}},
		{A: State{X: 11, Y: 1}, B: State{X: 10, Y: 2}},
		{A: State{X: 6, Y: 1}, B: State{X: 5, Y: 2}},
		{A: State{X: 1, Y: 3}, B: State{X: 2, Y: 4}},
		{A: State{X: 6, Y: 1}, B: State{X: 7, Y: 1}},
		{A: State{X: 9, Y: 1}, B: State{X: 9, Y: 2}},
		{A: State{X: 13, Y: 8}, B: State{X: 12, Y: 9}},
		{A: State{X: 2, Y: 3}, B: State{X: 2, Y: 4}},
		{A: State{X: 5, Y: 1}, B: State{X: 5, Y: 2}},
		{A: State{X: 10, Y: 1}, B: State{X: 9, Y: 2}},
		{A: State{X: 12, Y: 8}, B: State{X: 13, Y: 9}},
		{A: State{X: 10, Y: 1}, B: State{X: 11, Y: 1}},
		{A: State{X: 12, Y: 3}, B: State{X: 13, Y: 3}},
		{A: State{X: 2, Y: 1}, B: State{X: 3, Y: 2}},
		{A: State{X: 12, Y: 7}, B: State{X: 12, Y: 8}},
		{A: State{X: 12, Y: 5}, B: State{X: 13, Y: 5}},
		{A: State{X: 3, Y: 1}, B: State{X: 4, Y: 1}},
		{A: State{X: 6, Y: 2}, B: State{X: 7, Y: 2}},
		{A: State{X: 1, Y: 3}, B: State{X: 1, Y: 4}},
		{A: State{X: 3, Y: 1}, B: State{X: 2, Y: 2}},
		{A: State{X: 12, Y: 4}, B: State{X: 13, Y: 5}},
		{A: State{X: 6, Y: 1}, B: State{X: 6, Y: 2}},
		{A: State{X: 1, Y: 7}, B: State{X: 1, Y: 8}},
		{A: State{X: 2, Y: 3}, B: State{X: 1, Y: 4}},
		{A: State{X: 12, Y: 8}, B: State{X: 12, Y: 9}},
		{A: State{X: 9, Y: 1}, B: State{X: 10, Y: 2}},
		{A: State{X: 10, Y: 2}, B: State{X: 11, Y: 2}},
		{A: State{X: 10, Y: 1}, B: State{X: 10, Y: 2}},
		{A: State{X: 12, Y: 1}, B: State{X: 13, Y: 2}},
		{A: State{X: 5, Y: 1}, B: State{X: 6, Y: 2}},
		{A: State{X: 1, Y: 2}, B: State{X: 2, Y: 3}},
		{A: State{X: 2, Y: 7}, B: State{X: 2, Y: 8}},
		{A: State{X: 13, Y: 2}, B: State{X: 13, Y: 3}},
		{A: State{X: 7, Y: 1}, B: State{X: 7, Y: 2}},
		{A: State{X: 13, Y: 4}, B: State{X: 13, Y: 5}},
		{A: State{X: 2, Y: 8}, B: State{X: 1, Y: 9}},
		{A: State{X: 13, Y: 5}, B: State{X: 1, Y: 6}},
		{A: State{X: 1, Y: 4}, B: State{X: 1, Y: 5}},
		{A: State{X: 13, Y: 1}, B: State{X: 12, Y: 2}},
		{A: State{X: 1, Y: 1}, B: State{X: 1, Y: 2}},
		{A: State{X: 1, Y: 8}, B: State{X: 2, Y: 8}},
		{A: State{X: 2, Y: 1}, B: State{X: 1, Y: 2}},
		{A: State{X: 1, Y: 7}, B: State{X: 2, Y: 8}},
		{A: State{X: 13, Y: 7}, B: State{X: 12, Y: 8}},
		{A: State{X: 8, Y: 1}, B: State{X: 9, Y: 2}},
		{A: State{X: 2, Y: 1}, B: State{X: 3, Y: 1}},
		{A: State{X: 4, Y: 1}, B: State{X: 5, Y: 2}},
		{A: State{X: 13, Y: 2}, B: State{X: 12, Y: 3}},
		{A: State{X: 12, Y: 3}, B: State{X: 13, Y: 4}},
		{A: State{X: 11, Y: 1}, B: State{X: 11, Y: 2}},
		{A: State{X: 12, Y: 2}, B: State{X: 13, Y: 2}},
		{A: State{X: 12, Y: 1}, B: State{X: 11, Y: 2}},
	}

	UpperSide = Side{
		Pos: UpperPos,
		WinStates: []State{
			{13, 5},
			{13, 6},
			{13, 7},
		},
		LoseStates: []State{
			{1, 5},
			{1, 6},
			{1, 7},
		},
	}
	LowerSide = Side{
		Pos: LowerPos,
		WinStates: []State{
			{1, 5},
			{1, 6},
			{1, 7},
		},
		LoseStates: []State{
			{13, 5},
			{13, 6},
			{13, 7},
		},
	}
)
